# Generated by Django 2.2 on 2020-02-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSGenerate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
