# Generated by Django 2.2 on 2020-02-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POSGenerate', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
